#line 2 "context_link.cpp"

#line 4 "context_link.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer context_link__create_buffer
#define yy_delete_buffer context_link__delete_buffer
#define yy_flex_debug context_link__flex_debug
#define yy_init_buffer context_link__init_buffer
#define yy_flush_buffer context_link__flush_buffer
#define yy_load_buffer_state context_link__load_buffer_state
#define yy_switch_to_buffer context_link__switch_to_buffer
#define yyin context_link_in
#define yyleng context_link_leng
#define yylex context_link_lex
#define yylineno context_link_lineno
#define yyout context_link_out
#define yyrestart context_link_restart
#define yytext context_link_text
#define yywrap context_link_wrap
#define yyalloc context_link_alloc
#define yyrealloc context_link_realloc
#define yyfree context_link_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE context_link_restart(context_link_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int context_link_leng;

extern FILE *context_link_in, *context_link_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE context_link_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-context_link_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < context_link_leng; ++yyl )\
                    if ( context_link_text[yyl] == '\n' )\
                        --context_link_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up context_link_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up context_link_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via context_link_restart()), so that the user can continue scanning by
	 * just pointing context_link_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when context_link_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int context_link_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow context_link_wrap()'s to do buffer switches
 * instead of setting up a fresh context_link_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void context_link_restart (FILE *input_file  );
void context_link__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE context_link__create_buffer (FILE *file,int size  );
void context_link__delete_buffer (YY_BUFFER_STATE b  );
void context_link__flush_buffer (YY_BUFFER_STATE b  );
void context_link_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void context_link_pop_buffer_state (void );

static void context_link_ensure_buffer_stack (void );
static void context_link__load_buffer_state (void );
static void context_link__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER context_link__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE context_link__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE context_link__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE context_link__scan_bytes (yyconst char *bytes,int len  );

void *context_link_alloc (yy_size_t  );
void *context_link_realloc (void *,yy_size_t  );
void context_link_free (void *  );

#define yy_new_buffer context_link__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        context_link_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            context_link__create_buffer(context_link_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        context_link_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            context_link__create_buffer(context_link_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define context_link_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *context_link_in = (FILE *) 0, *context_link_out = (FILE *) 0;

typedef int yy_state_type;

extern int context_link_lineno;

int context_link_lineno = 1;

extern char *context_link_text;
#define yytext_ptr context_link_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up context_link_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	context_link_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 194
#define YY_END_OF_BUFFER 195
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[455] =
    {   0,
      192,  192,  195,  194,  192,  193,  194,  194,  191,  191,
      189,  189,  189,  189,  188,  188,  188,  188,  188,   99,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      101,  188,  100,  188,  184,  184,  184,  188,  188,  188,
      184,  188,  188,  188,  184,  192,    1,    0,    0,    0,
        0,  189,    0,  111,  112,  113,  188,  166,  188,  188,
      188,  188,  188,  188,  188,  102,  188,  154,  188,  188,
      188,  188,  188,  188,  188,  188,  124,  188,  131,  188,
      125,  126,  110,  188,   94,  127,  188,  188,  188,  128,
      188,  188,  188,  188,  188,  188,  129,  188,  188,  188,

      188,  160,   62,  188,  188,  188,  188,  185,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  172,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  130,  188,
      188,  188,  188,  188,  188,  187,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  186,    1,    0,
        2,    0,    0,    0,    0,  190,  167,  168,   20,   53,
       54,  188,  188,  169,   92,   90,  103,  104,  188,  155,
      156,   76,  188,   36,  188,   49,   74,   55,   56,   57,
       58,  188,  188,  132,  140,   37,  139,  147,   22,   23,
      133,  141,  134,  142,   24,  135,  143,  151,   38,   25,

       78,  136,  144,   79,   59,   60,   52,   26,   61,  148,
      157,  137,  145,  163,   27,   28,  175,  107,  161,  162,
      188,  188,  188,  188,   48,   39,   40,  188,   95,   91,
       63,  188,   41,  108,   80,  105,   42,   64,  173,  174,
       65,   66,   67,  188,   50,   51,   43,   68,   69,   70,
      188,   34,   71,   72,   82,  188,   83,  138,  146,  188,
       84,   89,   85,   86,   87,   88,  109,  188,  188,   81,
       75,   73,  187,  188,  188,  188,   14,  188,  188,  188,
      188,  188,   17,  188,  186,    0,    0,   13,    0,    0,
      188,  188,  170,  171,   21,   93,  114,   77,   96,    0,

       10,  188,  188,  188,  152,  153,  149,  150,  158,  159,
      164,  165,  176,  177,  188,  188,   29,  188,   31,  188,
      115,  188,  188,  106,  188,  188,   44,  188,   46,  188,
      187,  188,  188,  188,   14,  188,  188,  188,  188,  188,
       18,  186,    0,    0,    0,    0,    0,  188,  188,   97,
      188,  188,  188,   30,   32,   33,  188,    0,    7,  188,
       35,   45,   47,  188,  188,  188,  188,  188,  188,  188,
      188,    0,    0,    0,    0,    0,  188,  188,  188,   98,
      188,    0,    8,  188,  188,  181,  188,   15,  188,  180,
      188,  188,  178,    0,    0,    0,    0,    0,  119,  120,

        0,    6,  188,    0,    9,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,   19,    0,   11,    0,    0,
        4,    0,  116,  117,  188,  188,  188,  179,  182,  188,
      188,    0,    5,   12,    0,    3,  188,  188,  188,  188,
       16,  188,  121,  118,  188,  188,  188,  188,  188,  188,
      122,  123,  183,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    7,    1,    1,    1,    7,
        7,    1,    8,    7,    8,    9,    1,   10,   11,   12,
       13,   14,   15,   15,   15,   15,   15,    7,    7,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        7,    1,    7,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   25,   50,   25,   25,   51,   52,   53,
       54,   55,   25,   56,   57,   58,   59,   60,   61,   62,
       61,   61,    7,    7,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    4,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst flex_int16_t yy_base[471] =
    {   0,
        0,    0,  748,  749,   61,  749,  742,   60,  749,   56,
       63,   70,   81,   92,   93,   81,  103,  101,  109,  107,
       78,  722,   76,    0,  122,  113,  134,  126,  135,  160,
      183,  143,   87,  154,  144,  171,    0,  102,  692,  690,
      179,  700,  695,  142,   25,  175,    0,  738,  684,  692,
      113,  227,  219,  749,  749,  749,    0,  214,  719,  718,
      703,  700,  714,  707,  705,  187,  707,  198,  699,  157,
      712,  691,  231,  692,  692,  706,  236,  712,  239,  705,
      241,  245,    0,  701,    0,  247,  709,  685,  688,  249,
      234,  689,   90,  690,  687,  694,  251,   95,  686,  692,

      694,  253,    0,  676,  677,  199,  671,  247,  248,  252,
      681,  671,  674,  691,  255,  670,  671,  265,  251,  262,
      673,  262,  681,  269,  667,  682,  657,  260,  283,  279,
      683,  289,  677,  662,  675,  264,  635,  638,  648,  632,
      632,  631,  635,  624,  629,  631,  624,  243,    0,  679,
      749,  627,  628,  623,  256,  311,    0,    0,    0,    0,
        0,  662,  644,  304,    0,    0,    0,    0,  649,    0,
        0,    0,  640,    0,  654,    0,  657,    0,    0,    0,
        0,  652,  326,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  306,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,  326,
      328,    0,    0,  330,    0,    0,  332,    0,    0,    0,
      640,  654,  321,  328,    0,    0,    0,  634,    0,    0,
        0,  639,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  648,    0,    0,    0,    0,    0,    0,
      631,    0,    0,    0,    0,  634,    0,    0,    0,  635,
        0,    0,    0,    0,    0,    0,    0,  324,  329,    0,
        0,    0,  305,  607,  619,  612,  356,  610,  600,  603,
      599,  598,    0,  597,  290,  307,  611,  749,  607,  595,
      611,  626,    0,    0,    0,    0,    0,    0,    0,  646,

      749,  371,  380,  401,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  612,  619,    0,  612,    0,  628,
        0,  625,  613,    0,  389,  624,    0,  607,    0,  623,
        0,  589,  580,  585,  574,  577,  583,  582,  573,  584,
        0,    0,  580,  573,  575,  573,  576,  351,  608,  410,
      421,  589,  430,    0,    0,    0,  585,  619,  749,  439,
        0,    0,    0,  577,  573,  443,  569,  560,  570,  560,
      553,  563,  570,  554,  555,  556,  590,  589,  458,  467,
      476,  604,  749,  485,  484,    0,  553,    0,  551,  562,
      547,  555,    0,  554,  548,  549,  595,  544,    0,    0,

      593,  749,  502,  592,  749,  517,  575,  574,  559,  555,
      570,  531,  535,  542,  504,    0,  512,  749,  469,  510,
      749,  509,    0,    0,  468,  482,  480,    0,    0,  443,
      432,  447,  749,  749,  446,  749,  404,  338,  318,  267,
        0,  262,    0,    0,  230,  388,  224,  197,  164,  135,
        0,    0,    0,  749,  524,  527,  530,  534,  538,  542,
      546,  550,  554,  558,  562,  566,  570,  574,  578,  582
    } ;

static yyconst flex_int16_t yy_def[471] =
    {   0,
      454,    1,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  454,  456,  457,  454,  454,
      454,  454,  454,  454,  454,  454,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,

      455,  455,  455,  455,  455,  455,  455,   30,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  456,  457,
      454,  454,  454,  454,  454,  454,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  458,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,

      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  454,  454,  454,  454,  454,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  459,

      454,  458,  458,  458,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  460,  455,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  454,  454,  454,  454,  454,  455,  455,  458,
      458,  455,  461,  455,  455,  455,  455,  462,  454,  460,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  454,  454,  454,  454,  454,  455,  455,  463,  458,
      464,  465,  454,  461,  455,  455,  455,  455,  455,  455,
      455,  455,  455,  454,  454,  454,  466,  454,  455,  455,

      467,  454,  463,  468,  454,  464,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  469,  454,  454,  466,
      454,  470,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  469,  454,  454,  470,  454,  455,  455,  455,  455,
      455,  455,  455,  455,  455,  455,  455,  455,  455,  455,
      455,  455,  455,    0,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454
    } ;

static yyconst flex_int16_t yy_nxt[812] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,    9,   11,
       12,   13,   14,   11,   11,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   24,   25,   26,   27,   28,
       29,   24,   30,   31,   32,   33,   24,   24,   34,   24,
       24,   24,   35,   36,   37,   24,   24,   38,   36,   39,
       24,   24,   24,   24,   40,   41,   42,   43,   24,   44,
       45,   45,   46,   48,   46,   52,   52,   52,   52,   52,
       52,   53,   52,   52,   52,   52,   52,   52,   53,   52,
       52,   52,   52,   52,   52,  148,  148,   84,   54,   53,
       52,   52,   52,   52,   52,   52,   85,   81,  131,   55,

       53,   52,   52,   52,   52,   52,   52,   63,  207,   58,
       56,   59,   82,   64,   49,  214,   50,  132,   65,   51,
       66,   60,   67,   68,   72,   61,  208,   62,   91,  215,
       69,   73,   70,   79,   74,   75,   92,   76,   71,   80,
       77,   86,   93,   87,  453,   88,  102,   78,   94,   95,
      105,   96,  138,   97,   89,  154,   90,  139,  103,  155,
      106,  104,  128,   98,  107,  133,   99,  100,  101,  108,
      108,  108,  108,  108,  108,  129,   46,  109,   46,  110,
      111,  130,  452,  134,  135,  173,  136,  136,  145,  112,
      174,  146,  136,  113,  114,  147,  167,  168,  115,  136,

      116,  137,  117,  118,  119,  120,  121,  170,  171,  122,
      223,  123,  224,  136,  136,  451,  124,  125,  126,  136,
      127,  136,  136,  157,  158,  142,  136,  136,  156,  156,
      156,  156,  156,  156,  136,   53,   52,   52,   52,   52,
       52,   52,  177,  178,  179,  184,  185,  159,  187,  188,
      191,  192,  204,  180,  193,  194,  196,  197,  202,  203,
      212,  213,  219,  220,   57,  226,   57,   57,  198,  228,
      242,  189,  205,  235,  239,  240,   57,  244,  227,  450,
       57,  248,  229,  447,  251,  243,  230,  256,  245,  236,
      252,  241,  258,  259,  246,  261,  249,  262,  257,  263,

      268,  446,  269,  285,  285,  264,  273,  273,  289,  265,
      266,  290,  273,  293,  294,  305,  306,  445,  260,  273,
      156,  156,  156,  156,  156,  156,  300,  300,  301,  300,
      300,  300,  300,  300,  300,  307,  308,  309,  310,  311,
      312,  313,  314,  317,  319,  329,  327,  331,  331,  303,
      342,  342,  444,  331,  343,  344,  318,  443,  304,  328,
      331,  377,  378,  320,  330,  335,  335,  335,  335,  335,
      335,  300,  300,  301,  300,  300,  300,  300,  300,  300,
      300,  300,  301,  300,  300,  300,  300,  300,  300,  358,
      358,  359,  358,  358,  358,  358,  358,  358,  448,  449,

      350,  300,  300,  301,  300,  300,  300,  300,  300,  300,
      300,  300,  301,  300,  300,  300,  300,  300,  300,  442,
      351,  300,  300,  301,  300,  300,  300,  300,  300,  300,
      382,  382,  383,  382,  382,  382,  382,  382,  382,  358,
      358,  359,  358,  358,  358,  358,  358,  358,  436,  433,
      441,  380,  388,  388,  388,  388,  388,  388,  401,  401,
      402,  401,  401,  401,  401,  401,  401,  300,  300,  301,
      300,  300,  300,  300,  300,  300,  404,  404,  405,  404,
      404,  404,  404,  404,  404,  382,  382,  383,  382,  382,
      382,  382,  382,  382,  407,  408,  440,  439,  438,  409,

      437,  410,  401,  401,  402,  401,  401,  401,  401,  401,
      401,  436,  421,  434,  433,  431,  411,  404,  404,  405,
      404,  404,  404,  404,  404,  404,   57,   57,  149,  149,
      150,  150,  150,  150,  302,  302,  302,  302,  300,  300,
      300,  300,  360,  360,  360,  360,  384,  384,  384,  384,
      358,  358,  358,  358,  403,  403,  403,  403,  406,  406,
      406,  406,  382,  382,  382,  382,  420,  420,  420,  420,
      401,  401,  401,  401,  404,  404,  404,  404,  432,  432,
      432,  432,  435,  435,  435,  435,  430,  429,  428,  427,
      426,  425,  424,  423,  405,  402,  422,  421,  419,  418,

      417,  416,  415,  414,  413,  412,  383,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  387,
      386,  359,  385,  381,  379,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  366,  365,  277,  364,  363,
      362,  361,  357,  356,  355,  354,  353,  352,  301,  349,
      348,  347,  346,  345,  341,  340,  339,  338,  337,  336,
      334,  333,  332,  326,  325,  324,  323,  322,  321,  316,
      315,  299,  298,  297,  296,  295,  292,  291,  288,  287,
      286,  151,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  272,  271,  270,  267,  255,  254,  253,

      250,  247,  238,  237,  234,  233,  232,  231,  225,  222,
      221,  218,  217,  216,  211,  210,  209,  206,  201,  200,
      199,  195,  190,  186,  183,  182,  181,  176,  175,  172,
      169,  166,  165,  164,  163,  162,  161,  160,  153,  152,
      151,  144,  143,  141,  140,   83,   47,  454,    3,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454
    } ;

static yyconst flex_int16_t yy_chk[812] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,   10,   10,   10,   10,   10,
       10,   11,   11,   11,   11,   11,   11,   11,   12,   12,
       12,   12,   12,   12,   12,   45,   45,   23,   12,   13,
       13,   13,   13,   13,   13,   13,   23,   21,   33,   13,

       14,   14,   14,   14,   14,   14,   14,   16,   93,   15,
       14,   15,   21,   16,    8,   98,    8,   33,   17,    8,
       17,   15,   17,   17,   18,   15,   93,   15,   26,   98,
       17,   18,   17,   20,   18,   19,   26,   19,   17,   20,
       19,   25,   26,   25,  450,   25,   28,   19,   26,   27,
       29,   27,   38,   27,   25,   51,   25,   38,   28,   51,
       29,   28,   32,   27,   29,   34,   27,   27,   27,   30,
       30,   30,   30,   30,   30,   32,   46,   30,   46,   30,
       30,   32,  449,   34,   34,   70,   35,   35,   44,   30,
       70,   44,   35,   30,   31,   44,   66,   66,   31,   35,

       31,   35,   31,   31,   31,   31,   31,   68,   68,   31,
      106,   31,  106,   36,   36,  448,   31,   31,   31,   36,
       31,   41,   41,   58,   58,   41,   36,   41,   53,   53,
       53,   53,   53,   53,   41,   52,   52,   52,   52,   52,
       52,   52,   73,   73,   73,   77,   77,   58,   79,   79,
       81,   81,   91,   73,   82,   82,   86,   86,   90,   90,
       97,   97,  102,  102,  108,  109,  108,  108,   86,  110,
      119,   79,   91,  115,  118,  118,  108,  120,  109,  447,
      108,  122,  110,  445,  124,  119,  110,  128,  120,  115,
      124,  118,  129,  129,  120,  130,  122,  130,  128,  130,

      132,  442,  132,  148,  148,  130,  136,  136,  155,  130,
      130,  155,  136,  164,  164,  198,  198,  440,  129,  136,
      156,  156,  156,  156,  156,  156,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  210,  210,  211,  211,  214,
      214,  217,  217,  223,  224,  269,  268,  273,  273,  183,
      285,  285,  439,  273,  286,  286,  223,  438,  183,  268,
      273,  348,  348,  224,  269,  277,  277,  277,  277,  277,
      277,  302,  302,  302,  302,  302,  302,  302,  302,  302,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  446,  446,

      303,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  437,
      304,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  435,  432,
      431,  351,  366,  366,  366,  366,  366,  366,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  380,  380,  380,
      380,  380,  380,  380,  380,  380,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  385,  385,  430,  427,  426,  385,

      425,  385,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  422,  420,  419,  417,  415,  385,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  455,  455,  456,  456,
      457,  457,  457,  457,  458,  458,  458,  458,  459,  459,
      459,  459,  460,  460,  460,  460,  461,  461,  461,  461,
      462,  462,  462,  462,  463,  463,  463,  463,  464,  464,
      464,  464,  465,  465,  465,  465,  466,  466,  466,  466,
      467,  467,  467,  467,  468,  468,  468,  468,  469,  469,
      469,  469,  470,  470,  470,  470,  414,  413,  412,  411,
      410,  409,  408,  407,  404,  401,  398,  397,  396,  395,

      394,  392,  391,  390,  389,  387,  382,  378,  377,  376,
      375,  374,  373,  372,  371,  370,  369,  368,  367,  365,
      364,  358,  357,  352,  349,  347,  346,  345,  344,  343,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  330,
      328,  326,  323,  322,  320,  318,  316,  315,  300,  292,
      291,  290,  289,  287,  284,  282,  281,  280,  279,  278,
      276,  275,  274,  260,  256,  251,  244,  232,  228,  222,
      221,  182,  177,  175,  173,  169,  163,  162,  154,  153,
      152,  150,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  135,  134,  133,  131,  127,  126,  125,

      123,  121,  117,  116,  114,  113,  112,  111,  107,  105,
      104,  101,  100,   99,   96,   95,   94,   92,   89,   88,
       87,   84,   80,   78,   76,   75,   74,   72,   71,   69,
       67,   65,   64,   63,   62,   61,   60,   59,   50,   49,
       48,   43,   42,   40,   39,   22,    7,    3,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[195] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int context_link__flex_debug;
int context_link__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *context_link_text;
#line 1 "context_link.l"
#line 10 "context_link.l"
#include "context_link.tab.h"
#include "context.h"
#include "context_link_def.h"

#define COL_NO context_link_col+=strlen(context_link_text)

unsigned int context_link_col = 0;

extern int context_link_parse();
extern programObject t_program;
extern unsigned int shaderType;
#line 853 "context_link.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int context_link_lex_destroy (void );

int context_link_get_debug (void );

void context_link_set_debug (int debug_flag  );

YY_EXTRA_TYPE context_link_get_extra (void );

void context_link_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *context_link_get_in (void );

void context_link_set_in  (FILE * in_str  );

FILE *context_link_get_out (void );

void context_link_set_out  (FILE * out_str  );

int context_link_get_leng (void );

char *context_link_get_text (void );

int context_link_get_lineno (void );

void context_link_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int context_link_wrap (void );
#else
extern int context_link_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( context_link_text, context_link_leng, 1, context_link_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( context_link_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( context_link_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, context_link_in))==0 && ferror(context_link_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(context_link_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int context_link_lex (void);

#define YY_DECL int context_link_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after context_link_text and context_link_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 23 "context_link.l"


#line 1043 "context_link.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! context_link_in )
			context_link_in = stdin;

		if ( ! context_link_out )
			context_link_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			context_link_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				context_link__create_buffer(context_link_in,YY_BUF_SIZE );
		}

		context_link__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of context_link_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 455 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 749 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < context_link_leng; ++yyl )
				if ( context_link_text[yyl] == '\n' )
					   
    context_link_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 25 "context_link.l"
/* Compiler's name */
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 26 "context_link.l"
/* Comment */
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 27 "context_link.l"

	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 28 "context_link.l"

	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 29 "context_link.l"

	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 30 "context_link.l"

	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 31 "context_link.l"

	YY_BREAK
case 8:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 32 "context_link.l"

	YY_BREAK
case 9:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 33 "context_link.l"

	YY_BREAK
case 10:
*yy_cp = (yy_hold_char); /* undo effects of setting up context_link_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up context_link_text again */
YY_RULE_SETUP
#line 34 "context_link.l"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 36 "context_link.l"
COL_NO; return PROG;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 37 "context_link.l"
COL_NO; return SEMT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 38 "context_link.l"
COL_NO; return VAR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 39 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return TYPE;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return TYPE;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return TYPE;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "context_link.l"
COL_NO;	return VIN;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "context_link.l"
COL_NO;	return VOUT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "context_link.l"
COL_NO;	return TEXTURE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ABS; return VECTOROP;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "context_link.l"
COL_NO;	context_link_lval.ival=OP_CEIL; return VECTOROP;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "context_link.l"
COL_NO;	context_link_lval.ival=OP_FLR; return VECTOROP;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "context_link.l"
COL_NO;	context_link_lval.ival=OP_FRC; return VECTOROP;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "context_link.l"
COL_NO;	context_link_lval.ival=OP_I2F; return VECTOROP;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "context_link.l"
COL_NO;	context_link_lval.ival=OP_LIT; return VECTOROP;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MOV; return VECTOROP;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "context_link.l"
COL_NO;	context_link_lval.ival=OP_NOT; return VECTOROP;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "context_link.l"
COL_NO;	context_link_lval.ival=OP_NRM; return VECTOROP;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "context_link.l"
COL_NO;	context_link_lval.ival=OP_PK2H; return VECTOROP;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "context_link.l"
COL_NO;	context_link_lval.ival=OP_PK2US; return VECTOROP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "context_link.l"
COL_NO;	context_link_lval.ival=OP_PK4B; return VECTOROP;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "context_link.l"
COL_NO;	context_link_lval.ival=OP_PK4UB; return VECTOROP;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ROUND; return VECTOROP;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SSG; return VECTOROP;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TRUNC; return VECTOROP;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "context_link.l"
COL_NO;	context_link_lval.ival=OP_COS; return SCALAROP;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "context_link.l"
COL_NO;	context_link_lval.ival=OP_EX2; return SCALAROP;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "context_link.l"
COL_NO;	context_link_lval.ival=OP_LG2; return SCALAROP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "context_link.l"
COL_NO;	context_link_lval.ival=OP_RCC; return SCALAROP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "context_link.l"
COL_NO;	context_link_lval.ival=OP_RCP; return SCALAROP;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "context_link.l"
COL_NO;	context_link_lval.ival=OP_RSQ; return SCALAROP;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SCS; return SCALAROP;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SIN; return SCALAROP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "context_link.l"
COL_NO;	context_link_lval.ival=OP_UP2H; return SCALAROP;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "context_link.l"
COL_NO;	context_link_lval.ival=OP_UP2US; return SCALAROP;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "context_link.l"
COL_NO;	context_link_lval.ival=OP_UP4B; return SCALAROP;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "context_link.l"
COL_NO;	context_link_lval.ival=OP_UP4UB; return SCALAROP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "context_link.l"
COL_NO;	context_link_lval.ival=OP_POW;  return BINSCOP;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DIV; return VECSCAOP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SHL; return VECSCAOP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SHR; return VECSCAOP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MOD; return VECSCAOP;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ADD; return BINOP;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "context_link.l"
COL_NO;	context_link_lval.ival=OP_AND; return BINOP;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DP3; return BINOP;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DP4; return BINOP;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DPH; return BINOP;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DST; return BINOP;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MAX; return BINOP;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MIN; return BINOP;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MUL; return BINOP;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "context_link.l"
COL_NO;	context_link_lval.ival=OP_OR; return BINOP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "context_link.l"
COL_NO;	context_link_lval.ival=OP_RFL; return BINOP;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SEQ; return BINOP;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SFL; return BINOP;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SGE; return BINOP;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SGT; return BINOP;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SLE; return BINOP;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SLT; return BINOP;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SNE; return BINOP;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "context_link.l"
COL_NO;	context_link_lval.ival=OP_STR; return BINOP;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SUB; return BINOP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "context_link.l"
COL_NO;	context_link_lval.ival=OP_XPD; return BINOP;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DP2; return BINOP;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "context_link.l"
COL_NO;	context_link_lval.ival=OP_XOR; return BINOP;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "context_link.l"
COL_NO;	context_link_lval.ival=OP_CMP; return TRIOP;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "context_link.l"
COL_NO;	context_link_lval.ival=OP_DP2A; return TRIOP;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 113 "context_link.l"
COL_NO;	context_link_lval.ival=OP_LRP; return TRIOP;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 114 "context_link.l"
COL_NO;	context_link_lval.ival=OP_MAD; return TRIOP;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 115 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SAD; return TRIOP;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 116 "context_link.l"
COL_NO;	context_link_lval.ival=OP_X2D; return TRIOP;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 117 "context_link.l"
COL_NO;	context_link_lval.ival=OP_SWZ; return SWZOP;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 118 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TEX; return TEXOP;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 119 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXB; return TEXOP;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 120 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXF; return TEXOP;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 121 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXL; return TEXOP;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 122 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXP; return TEXOP;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 123 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXQ; return TEXOP;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 124 "context_link.l"
COL_NO;	context_link_lval.ival=OP_TXD; return TXDOP;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 125 "context_link.l"
COL_NO;	context_link_lval.ival=OP_CAL; return BRAOP;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 126 "context_link.l"
COL_NO;	context_link_lval.ival=OP_RET; return FLOWCCOP;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 127 "context_link.l"
COL_NO;	context_link_lval.ival=OP_BRK; return FLOWCCOP;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 128 "context_link.l"
COL_NO;	context_link_lval.ival=OP_CONT; return FLOWCCOP;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 129 "context_link.l"
COL_NO;	context_link_lval.ival=OP_IF; return IFOP;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 130 "context_link.l"
COL_NO;	context_link_lval.ival=OP_REP; return REPOP;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 131 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ELSE; return ENDFLOWOP;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 132 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ENDIF; return ENDFLOWOP;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 133 "context_link.l"
COL_NO;	context_link_lval.ival=OP_ENDREP; return ENDFLOWOP;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 134 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_F; return OPMODIFIER;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 135 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_U; return OPMODIFIER;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 136 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_S; return OPMODIFIER;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 137 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_CC; return OPMODIFIER;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 138 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_CC0; return OPMODIFIER;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 139 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_CC1; return OPMODIFIER;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 140 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_SAT; return OPMODIFIER;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 141 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_SSAT; return OPMODIFIER;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 142 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_NTC; return OPMODIFIER;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 143 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_S24; return OPMODIFIER;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 144 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_U24; return OPMODIFIER;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 145 "context_link.l"
COL_NO;	context_link_lval.ival=OPM_HI; return OPMODIFIER;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 146 "context_link.l"
COL_NO;	context_link_lval.ival=TT_1D; return TEXTARGET;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 147 "context_link.l"
COL_NO;	context_link_lval.ival=TT_2D; return TEXTARGET;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 148 "context_link.l"
COL_NO;	context_link_lval.ival=TT_3D; return TEXTARGET;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 149 "context_link.l"
COL_NO;	context_link_lval.ival=TT_CUBE; return TEXTARGET;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 150 "context_link.l"
COL_NO;	context_link_lval.ival=TT_RECT; return TEXTARGET;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 151 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOW1D; return TEXTARGET;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 152 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOW2D; return TEXTARGET;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 153 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOWRECT; return TEXTARGET;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 154 "context_link.l"
COL_NO;	context_link_lval.ival=TT_ARRAY1D; return TEXTARGET;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 155 "context_link.l"
COL_NO;	context_link_lval.ival=TT_ARRAY2D; return TEXTARGET;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 156 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOWCUBE; return TEXTARGET;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 157 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOWARRAY1D; return TEXTARGET;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 158 "context_link.l"
COL_NO;	context_link_lval.ival=TT_SHADOWARRAY2D; return TEXTARGET;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 159 "context_link.l"
COL_NO;	context_link_lval.ival=CC_EQ; return CCMASKRULE;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 160 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GE; return CCMASKRULE;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 161 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GT; return CCMASKRULE;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 162 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LE; return CCMASKRULE;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 163 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LT; return CCMASKRULE;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 164 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NE; return CCMASKRULE;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 165 "context_link.l"
COL_NO;	context_link_lval.ival=CC_TR; return CCMASKRULE;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 166 "context_link.l"
COL_NO;	context_link_lval.ival=CC_FL; return CCMASKRULE;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 167 "context_link.l"
COL_NO;	context_link_lval.ival=CC_EQ0; return CCMASKRULE;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 168 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GE0; return CCMASKRULE;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 169 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GT0; return CCMASKRULE;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 170 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LE0; return CCMASKRULE;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 171 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LT0; return CCMASKRULE;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 172 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NE0; return CCMASKRULE;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 173 "context_link.l"
COL_NO;	context_link_lval.ival=CC_TR0; return CCMASKRULE;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 174 "context_link.l"
COL_NO;	context_link_lval.ival=CC_FL0; return CCMASKRULE;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 175 "context_link.l"
COL_NO;	context_link_lval.ival=CC_EQ1; return CCMASKRULE;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 176 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GE1; return CCMASKRULE;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 177 "context_link.l"
COL_NO;	context_link_lval.ival=CC_GT1; return CCMASKRULE;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 178 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LE1; return CCMASKRULE;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 179 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LT1; return CCMASKRULE;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 180 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NE1; return CCMASKRULE;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 181 "context_link.l"
COL_NO;	context_link_lval.ival=CC_TR1; return CCMASKRULE;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 182 "context_link.l"
COL_NO;	context_link_lval.ival=CC_FL1; return CCMASKRULE;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 183 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NAN; return CCMASKRULE;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 184 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NAN0; return CCMASKRULE;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 185 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NAN1; return CCMASKRULE;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 186 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LEG; return CCMASKRULE;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 187 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LEG0; return CCMASKRULE;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 188 "context_link.l"
COL_NO;	context_link_lval.ival=CC_LEG1; return CCMASKRULE;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 189 "context_link.l"
COL_NO;	context_link_lval.ival=CC_CF; return CCMASKRULE;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 190 "context_link.l"
COL_NO;	context_link_lval.ival=CC_CF0; return CCMASKRULE;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 191 "context_link.l"
COL_NO;	context_link_lval.ival=CC_CF1; return CCMASKRULE;
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 192 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NCF; return CCMASKRULE;
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 193 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NCF0; return CCMASKRULE;
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 194 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NCF1; return CCMASKRULE;
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 195 "context_link.l"
COL_NO;	context_link_lval.ival=CC_OF; return CCMASKRULE;
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 196 "context_link.l"
COL_NO;	context_link_lval.ival=CC_OF0; return CCMASKRULE;
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 197 "context_link.l"
COL_NO;	context_link_lval.ival=CC_OF1; return CCMASKRULE;
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 198 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NOF; return CCMASKRULE;
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 199 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NOF0; return CCMASKRULE;
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 200 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NOF1; return CCMASKRULE;
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 201 "context_link.l"
COL_NO;	context_link_lval.ival=CC_AB; return CCMASKRULE;
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 202 "context_link.l"
COL_NO;	context_link_lval.ival=CC_AB0; return CCMASKRULE;
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 203 "context_link.l"
COL_NO;	context_link_lval.ival=CC_AB1; return CCMASKRULE;
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 204 "context_link.l"
COL_NO;	context_link_lval.ival=CC_BLE; return CCMASKRULE;
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 205 "context_link.l"
COL_NO;	context_link_lval.ival=CC_BLE0; return CCMASKRULE;
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 206 "context_link.l"
COL_NO;	context_link_lval.ival=CC_BLE1; return CCMASKRULE;
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 207 "context_link.l"
COL_NO;	context_link_lval.ival=CC_SF; return CCMASKRULE;
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 208 "context_link.l"
COL_NO;	context_link_lval.ival=CC_SF0; return CCMASKRULE;
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 209 "context_link.l"
COL_NO;	context_link_lval.ival=CC_SF1; return CCMASKRULE;
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 210 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NSF; return CCMASKRULE;
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 211 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NSF0; return CCMASKRULE;
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 212 "context_link.l"
COL_NO;	context_link_lval.ival=CC_NSF1; return CCMASKRULE;
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 213 "context_link.l"
COL_NO; return VERTEX;
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 214 "context_link.l"
COL_NO; return FRAGMENT;
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 215 "context_link.l"
COL_NO; return RESULT;
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 216 "context_link.l"
COL_NO; return ATTRIB;
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 217 "context_link.l"
COL_NO; return POSITION;
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 218 "context_link.l"
COL_NO; return RESULT_COLOR0;
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 219 "context_link.l"
COL_NO;	return *context_link_text;
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 220 "context_link.l"
{ COL_NO;
		char *temp = context_link_text+1;
		context_link_lval.ival=atoi(temp);
		return REG;
	}
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 225 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return XYZW_SWIZZLE;
	}
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 229 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return RGBA_SWIZZLE;
	}
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 233 "context_link.l"
{ COL_NO;
		strcpy(context_link_lval.sval,context_link_text);
		return IDENTIFIER;
	}
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 237 "context_link.l"
{ COL_NO;
		context_link_lval.ival = atoi(context_link_text);
		return INTEGER;
	}
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 241 "context_link.l"
{ COL_NO;
		context_link_lval.ival = atof(context_link_text);
		return FLOAT;
	}
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 245 "context_link.l"
COL_NO; return *context_link_text;
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 247 "context_link.l"
COL_NO;		/* remove all space-related char */
	YY_BREAK
case 193:
/* rule 193 can match eol */
YY_RULE_SETUP
#line 248 "context_link.l"
context_link_col = 0;
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 249 "context_link.l"
ECHO;
	YY_BREAK
#line 2162 "context_link.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed context_link_in at a new source and called
			 * context_link_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = context_link_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( context_link_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * context_link_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of context_link_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					context_link_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			context_link_restart(context_link_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) context_link_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 455 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 455 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 454);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up context_link_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --context_link_lineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					context_link_restart(context_link_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( context_link_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve context_link_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    context_link_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void context_link_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        context_link_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            context_link__create_buffer(context_link_in,YY_BUF_SIZE );
	}

	context_link__init_buffer(YY_CURRENT_BUFFER,input_file );
	context_link__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void context_link__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		context_link_pop_buffer_state();
	 *		context_link_push_buffer_state(new_buffer);
     */
	context_link_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	context_link__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (context_link_wrap()) processing, but the only time this flag
	 * is looked at is after context_link_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void context_link__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	context_link_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE context_link__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) context_link_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in context_link__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) context_link_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in context_link__create_buffer()" );

	b->yy_is_our_buffer = 1;

	context_link__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with context_link__create_buffer()
 * 
 */
    void context_link__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		context_link_free((void *) b->yy_ch_buf  );

	context_link_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a context_link_restart() or at EOF.
 */
    static void context_link__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	context_link__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then context_link__init_buffer was _probably_
     * called from context_link_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void context_link__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		context_link__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void context_link_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	context_link_ensure_buffer_stack();

	/* This block is copied from context_link__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from context_link__switch_to_buffer. */
	context_link__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void context_link_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	context_link__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		context_link__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void context_link_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)context_link_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in context_link_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)context_link_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in context_link_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE context_link__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) context_link_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in context_link__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	context_link__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to context_link_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       context_link__scan_bytes() instead.
 */
YY_BUFFER_STATE context_link__scan_string (yyconst char * yystr )
{
    
	return context_link__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to context_link_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE context_link__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) context_link_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in context_link__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = context_link__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in context_link__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up context_link_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		context_link_text[context_link_leng] = (yy_hold_char); \
		(yy_c_buf_p) = context_link_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		context_link_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int context_link_get_lineno  (void)
{
        
    return context_link_lineno;
}

/** Get the input stream.
 * 
 */
FILE *context_link_get_in  (void)
{
        return context_link_in;
}

/** Get the output stream.
 * 
 */
FILE *context_link_get_out  (void)
{
        return context_link_out;
}

/** Get the length of the current token.
 * 
 */
int context_link_get_leng  (void)
{
        return context_link_leng;
}

/** Get the current token.
 * 
 */

char *context_link_get_text  (void)
{
        return context_link_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void context_link_set_lineno (int  line_number )
{
    
    context_link_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see context_link__switch_to_buffer
 */
void context_link_set_in (FILE *  in_str )
{
        context_link_in = in_str ;
}

void context_link_set_out (FILE *  out_str )
{
        context_link_out = out_str ;
}

int context_link_get_debug  (void)
{
        return context_link__flex_debug;
}

void context_link_set_debug (int  bdebug )
{
        context_link__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from context_link_lex_destroy(), so don't allocate here.
     */

    /* We do not touch context_link_lineno unless the option is enabled. */
    context_link_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    context_link_in = stdin;
    context_link_out = stdout;
#else
    context_link_in = (FILE *) 0;
    context_link_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * context_link_lex_init()
     */
    return 0;
}

/* context_link_lex_destroy is for both reentrant and non-reentrant scanners. */
int context_link_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		context_link__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		context_link_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	context_link_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * context_link_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *context_link_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *context_link_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void context_link_free (void * ptr )
{
	free( (char *) ptr );	/* see context_link_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 249 "context_link.l"



void context_link_error(char *s)
{
    printf("(%d,%d) %s at %s\n",
			context_link_lineno,
			context_link_col,
			s,
			context_link_text);
}

void Context::LinkProgram(GLuint program)
{
	shaderObject VS, FS;
	VS = shaderPool[programPool[program].sid4VS];
	FS = shaderPool[programPool[program].sid4FS];
	
	if (programPool.find(program) == programPool.end()) {
		RecordError(GL_INVALID_VALUE);
		return;
	}
	
	if (programPool[program].isLinked == GL_TRUE)
		return;
	
	if ((programPool[program].sid4VS == 0) || (programPool[program].sid4FS == 0)) {
		programPool[program].linkStatus = LS_SHADER_MISSING;
		programPool[program].linkInfo = "A vertex shader and a fragment shader are not both present in the program object.";
		return;
	}
	else if ((VS.isCompiled == GL_FALSE) || (FS.isCompiled == GL_FALSE)) {
		programPool[program].linkStatus = LS_SHADER_IS_NOT_COMPILED;
		programPool[program].linkInfo = "One or more of the attached shader objects has not been successfully compiled or loaded with a pre-compiled shader binary.";
		return;
	}
	
	t_program = programPool[program];
		
	context_link_lineno = 1;
	shaderType = 0;
	context_link__scan_string(VS.asmSrc.c_str());
	context_link_parse();
	
	printf("\n");

	context_link_lineno = 1;
	shaderType = 1;
	context_link__scan_string(FS.asmSrc.c_str());
	context_link_parse();
	
	///Check both's shader's in/output are matched.
	std::map<std::string, symbol>::iterator it;
	for (it = t_program.symbolVSout.begin(); it!=t_program.symbolVSout.end(); it++) {
		if (t_program.symbolFSin.find(it->first) == t_program.symbolFSin.end()) {
			programPool[program].linkStatus = LS_VS_FS_VARRYING_UNMATCH;
			printf("%s \n",it->first.c_str());
			return;
		}
		else {
			if (t_program.symbolVSout[it->first].declareType != 
			    t_program.symbolFSin[it->first].declareType) {
				programPool[program].linkStatus = LS_VS_FS_VARRYING_UNMATCH;
				printf("%s \n",it->first.c_str());
				return;
			}
		}
	}
	
	t_program.linkInfo.clear();
	
//	printf("\nVSin: ");
//	for (it = t_program.symbolVSin.begin(); it!=t_program.symbolVSin.end(); it++)
//		printf("%s ",it->first.c_str());
//	printf("\nVSout: ");
//	for (it = t_program.symbolVSout.begin(); it!=t_program.symbolVSout.end(); it++)
//		printf("%s ",it->first.c_str());
//	printf("\nVSin: ");
//	for (it = t_program.symbolFSin.begin(); it!=t_program.symbolFSin.end(); it++)
//		printf("%s ",it->first.c_str());
//	printf("\nVSout: ");
//	for (it = t_program.symbolFSout.begin(); it!=t_program.symbolFSout.end(); it++)
//		printf("%s ",it->first.c_str());
//	printf("\nUniform: ");
//	for (it = t_program.symbolUniform.begin(); it!=t_program.symbolUniform.end(); it++)
//		printf("%s ",it->first.c_str());
//	printf("\n");
	
	programPool[program] = t_program;
	programPool[program].linkStatus = LS_NO_ERROR;
	programPool[program].isLinked = GL_TRUE;
	
}

