#line 2 "nvgp4ASM.cpp"

#line 4 "nvgp4ASM.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer nvgp4ASM__create_buffer
#define yy_delete_buffer nvgp4ASM__delete_buffer
#define yy_flex_debug nvgp4ASM__flex_debug
#define yy_init_buffer nvgp4ASM__init_buffer
#define yy_flush_buffer nvgp4ASM__flush_buffer
#define yy_load_buffer_state nvgp4ASM__load_buffer_state
#define yy_switch_to_buffer nvgp4ASM__switch_to_buffer
#define yyin nvgp4ASM_in
#define yyleng nvgp4ASM_leng
#define yylex nvgp4ASM_lex
#define yylineno nvgp4ASM_lineno
#define yyout nvgp4ASM_out
#define yyrestart nvgp4ASM_restart
#define yytext nvgp4ASM_text
#define yywrap nvgp4ASM_wrap
#define yyalloc nvgp4ASM_alloc
#define yyrealloc nvgp4ASM_realloc
#define yyfree nvgp4ASM_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE nvgp4ASM_restart(nvgp4ASM_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int nvgp4ASM_leng;

extern FILE *nvgp4ASM_in, *nvgp4ASM_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE nvgp4ASM_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-nvgp4ASM_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < nvgp4ASM_leng; ++yyl )\
                    if ( nvgp4ASM_text[yyl] == '\n' )\
                        --nvgp4ASM_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nvgp4ASM_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via nvgp4ASM_restart()), so that the user can continue scanning by
	 * just pointing nvgp4ASM_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when nvgp4ASM_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int nvgp4ASM_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow nvgp4ASM_wrap()'s to do buffer switches
 * instead of setting up a fresh nvgp4ASM_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void nvgp4ASM_restart (FILE *input_file  );
void nvgp4ASM__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE nvgp4ASM__create_buffer (FILE *file,int size  );
void nvgp4ASM__delete_buffer (YY_BUFFER_STATE b  );
void nvgp4ASM__flush_buffer (YY_BUFFER_STATE b  );
void nvgp4ASM_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void nvgp4ASM_pop_buffer_state (void );

static void nvgp4ASM_ensure_buffer_stack (void );
static void nvgp4ASM__load_buffer_state (void );
static void nvgp4ASM__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER nvgp4ASM__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE nvgp4ASM__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE nvgp4ASM__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE nvgp4ASM__scan_bytes (yyconst char *bytes,int len  );

void *nvgp4ASM_alloc (yy_size_t  );
void *nvgp4ASM_realloc (void *,yy_size_t  );
void nvgp4ASM_free (void *  );

#define yy_new_buffer nvgp4ASM__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        nvgp4ASM_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nvgp4ASM__create_buffer(nvgp4ASM_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        nvgp4ASM_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nvgp4ASM__create_buffer(nvgp4ASM_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define nvgp4ASM_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *nvgp4ASM_in = (FILE *) 0, *nvgp4ASM_out = (FILE *) 0;

typedef int yy_state_type;

extern int nvgp4ASM_lineno;

int nvgp4ASM_lineno = 1;

extern char *nvgp4ASM_text;
#define yytext_ptr nvgp4ASM_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up nvgp4ASM_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	nvgp4ASM_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 201
#define YY_END_OF_BUFFER 202
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[478] =
    {   0,
      199,  199,  202,  201,  199,  200,  201,  198,  198,  196,
      196,  196,  196,  195,  195,  195,  195,  195,  103,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      105,  195,  104,  195,  189,  189,  189,  195,  189,  195,
      189,  195,  195,  189,  201,  199,    0,    0,    0,    0,
      196,    0,  115,  116,  117,  195,  170,  195,  195,  195,
      195,  195,  195,  195,  106,  195,  158,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  128,  195,  135,  195,
      129,  130,  190,  114,  195,   95,  195,  131,  195,  195,
      195,  132,  195,  195,  195,  195,  195,  195,  133,  195,

      195,  195,  195,  164,   63,  195,  195,  195,  195,  192,
      191,  195,  195,  195,  195,  195,  195,  195,  195,  176,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  134,  195,  195,  195,  195,  195,  195,  194,  195,
      195,  195,  195,  195,  195,  195,  193,    0,    7,    0,
        1,    0,    0,    0,    0,  197,  171,  172,   21,   54,
       55,  195,  195,  173,   93,   91,  107,  108,  195,  195,
      159,  160,   77,  195,   37,  195,  101,  102,   50,   75,
       56,   57,   58,   59,  195,   14,  136,  144,   38,  143,
      151,  195,   23,   24,  137,  145,  138,  146,   25,  100,

      139,  147,  155,   39,   26,   79,  140,  148,   80,   60,
       61,   53,   27,   62,  152,  161,  141,  149,  167,  195,
      195,   28,   29,  179,  111,  165,  166,  195,  195,  195,
      195,   49,   40,   41,  195,   96,   92,   64,  195,   42,
      112,   81,  109,   43,   65,  177,  178,   66,   67,   68,
      195,   51,   52,   44,   69,   70,  195,   71,  195,   35,
       72,   73,   83,  195,   84,  142,  150,  195,   85,   90,
       86,   87,   88,   89,  113,  195,  195,   82,   76,   74,
      194,  195,  195,  195,  195,  195,  195,  195,  193,    0,
        0,    0,    0,    0,    0,  195,  195,  174,  175,   22,

      195,   94,  118,   78,   97,  195,  195,   17,  156,  157,
      153,  154,  162,  163,  168,  169,  195,  195,  180,  181,
      195,  195,   30,  195,   32,  195,  119,  195,  195,  195,
      110,  195,  195,   45,  195,   47,  195,  194,  195,  195,
      195,  195,  195,  195,  195,  195,  193,    0,    0,    0,
        0,    6,    0,    0,    0,  197,  195,  195,  195,   98,
      195,  195,  195,  195,  195,   31,   33,   34,  195,  195,
        0,    8,  195,   36,   46,   48,  195,  195,   13,   12,
      195,  195,  195,  195,    0,    0,    0,    0,    0,  195,
      195,  186,  195,   99,  195,  195,  195,    0,    9,  195,

      195,   16,  185,  195,  195,  184,  195,  182,    0,    0,
        0,    0,    0,  123,  124,  195,  195,  195,    0,   10,
      195,  195,  195,  195,  195,  195,  195,  195,  195,   15,
       11,    0,    0,    0,    3,    0,   18,  195,  195,  120,
      121,  195,  195,  195,  183,  187,  195,    0,    4,    0,
        0,    2,  195,   20,  195,  195,  195,  195,    0,    5,
      195,  195,  125,  122,  195,  195,  195,  195,  195,  195,
      195,  195,   19,  126,  127,  188,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    1,    6,    7,    1,    1,    1,    7,
        7,    1,    8,    7,    8,    9,    1,   10,   11,   12,
       13,   14,   15,   15,   15,   15,   15,    7,    7,    1,
        7,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        7,    1,    7,    1,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   25,   50,   25,   25,   51,   52,   53,
       54,   55,   25,   56,   57,   58,   59,   60,   61,   62,
       61,   61,    7,    7,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    } ;

static yyconst flex_int16_t yy_base[492] =
    {   0,
        0,  669,  673,  675,   61,  675,   60,  675,   56,   63,
       70,   81,   92,   93,   81,  103,  106,  109,  102,   78,
      125,   76,    0,  648,  122,  129,  134,  130,  144,  165,
      188,  151,   87,  161,  138,  158,    0,  615,  176,  616,
      186,  622,  621,   25,  664,  130,  663,  609,  617,  115,
      234,  226,  675,  675,  675,    0,  187,  644,  643,  628,
      625,  639,  632,  630,  178,  132,  217,  625,  184,  638,
      211,  617,  240,  618,  618,  632,  245,  638,  248,  631,
      250,  255,    0,    0,  627,    0,  620,  257,  634,  610,
      613,  259,  108,  614,  238,  615,  612,  619,  261,  252,

      611,  617,  619,  266,    0,  601,  602,  191,  596,  268,
      260,  262,  606,  596,  599,  616,  255,  595,  596,  284,
      264,  276,  598,  280,  596,  605,  285,  591,  606,  581,
      277,  302,  287,  607,  308,  601,  586,  599,  280,  559,
      573,  601,  557,  556,  550,  555,  264,  607,  675,  606,
      675,  554,  555,  550,  274,  329,    0,    0,    0,    0,
        0,  589,  571,  321,    0,    0,    0,    0,  576,  567,
        0,    0,    0,  566,    0,  580,    0,    0,    0,  583,
        0,    0,    0,    0,  578,  304,    0,    0,    0,    0,
        0,  562,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,  323,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  335,  337,    0,    0,  340,  576,
      567,    0,    0,  342,    0,    0,    0,  563,  577,  331,
      338,    0,    0,    0,  557,    0,    0,    0,  562,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      571,    0,    0,    0,    0,    0,  559,    0,  553,    0,
        0,    0,    0,  556,    0,    0,    0,  557,    0,    0,
        0,    0,    0,    0,    0,  333,  341,    0,    0,    0,
      316,  529,  535,  313,  533,  523,  523,  522,  301,  322,
      536,  575,  531,  519,  370,  535,  550,    0,    0,    0,

      540,    0,    0,    0,    0,  551,  551,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  537,  553,    0,    0,
      532,  539,    0,  532,    0,  548,    0,  545,  533,  527,
        0,  385,  543,    0,  526,    0,  542,    0,  508,  505,
      501,  500,  496,  502,  493,  504,    0,  500,  493,  495,
      544,  675,  492,  495,  385,  391,  396,  527,  513,    0,
      511,  507,  513,  504,  408,    0,    0,    0,  500,  514,
      533,  675,  417,    0,    0,    0,  491,  487,    0,    0,
      483,  474,  475,  468,  478,  485,  469,  470,  471,  505,
      504,    0,  498,    0,  490,  496,  426,  516,  675,  435,

      434,    0,    0,  465,  463,  474,  468,    0,  467,  461,
      462,  508,  457,    0,    0,  490,  488,  466,  503,  675,
      452,  486,  485,  470,  466,  481,  442,  446,  453,    0,
      675,  494,  451,  492,  675,  491,    0,  448,  445,    0,
        0,  431,  446,  444,    0,    0,  397,  446,  675,  376,
      372,  675,  333,    0,  350,  344,  322,  284,  318,  675,
      293,  270,    0,    0,  242,  245,  436,  206,  214,  174,
      153,  106,    0,    0,    0,    0,  675,  107,  467,  469,
      471,  473,  475,  477,  479,  481,  483,  485,  487,  489,
      491

    } ;

static yyconst flex_int16_t yy_def[492] =
    {   0,
      477,    1,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  479,  477,  480,  477,  477,  477,
      477,  477,  477,  477,  477,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,   30,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  479,  477,  480,
      477,  477,  477,  477,  477,  477,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  477,
      477,  481,  477,  477,  477,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  482,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  477,  477,  477,
      481,  477,  477,  477,  477,  477,  478,  478,  478,  478,
      478,  478,  478,  478,  483,  478,  478,  478,  478,  478,
      484,  477,  482,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  477,  477,  477,  477,  477,  478,
      478,  478,  478,  478,  478,  478,  485,  486,  477,  483,

      478,  478,  478,  478,  478,  478,  478,  478,  477,  477,
      477,  487,  477,  478,  478,  478,  478,  478,  488,  477,
      485,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      477,  489,  477,  487,  477,  490,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  489,  477,  491,
      490,  477,  478,  478,  478,  478,  478,  478,  491,  477,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,    0,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477

    } ;

static yyconst flex_int16_t yy_nxt[738] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    8,   10,
       11,   12,   13,   10,   10,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   23,   30,   31,   32,   33,   23,   23,   34,   23,
       23,   23,   35,   36,   37,   23,   23,   38,   39,   23,
       23,   23,   23,   23,   40,   41,   23,   42,   23,   43,
       44,   44,   46,   47,   46,   51,   51,   51,   51,   51,
       51,   52,   51,   51,   51,   51,   51,   51,   52,   51,
       51,   51,   51,   51,   51,  147,  147,   85,   53,   52,
       51,   51,   51,   51,   51,   51,   86,   81,  134,   54,

       52,   51,   51,   51,   51,   51,   51,   62,   56,   57,
       55,   58,   82,   63,   48,  476,   49,  135,   64,   50,
       65,   59,   66,   67,   71,   60,  209,   61,   79,   72,
       68,   46,   69,   46,   80,   75,   73,   76,   70,   74,
       77,   88,   83,   89,   93,   90,  210,   78,   84,   97,
      104,   98,   94,   99,   91,  169,   92,  154,   95,  107,
      170,  155,  105,  100,   96,  106,  101,  102,  103,  108,
      131,  475,  136,  109,  110,  110,  110,  110,  110,  110,
      139,  139,  111,  132,  112,  113,  139,  167,  168,  133,
      137,  138,  474,  139,  114,  140,  157,  158,  115,  116,

      139,  139,  230,  117,  231,  118,  139,  119,  120,  121,
      122,  123,  174,  139,  124,  125,  126,  175,  139,  139,
      159,  127,  128,  129,  139,  130,  171,  172,  139,  139,
      142,  139,  144,  473,  139,  156,  156,  156,  156,  156,
      156,  139,   52,   51,   51,   51,   51,   51,   51,  177,
      178,  180,  181,  182,  187,  188,  212,  190,  191,  195,
      196,  472,  183,  192,  197,  198,  201,  202,  207,  208,
      217,  218,  219,  242,  213,  226,  227,  233,  203,  235,
      193,  469,  220,  249,  221,   56,  222,   56,   56,  243,
      234,  251,  236,  246,  247,  468,  237,   56,  250,  255,

      259,   56,  252,  269,  264,  270,  260,  271,  253,  467,
      248,  266,  267,  272,  256,  265,  466,  273,  274,  276,
      460,  277,  281,  281,  289,  289,  293,  306,  281,  294,
      298,  299,  309,  310,  465,  281,  307,  268,  156,  156,
      156,  156,  156,  156,  311,  312,  313,  314,  295,  315,
      316,  319,  320,  323,  325,  334,  464,  336,  338,  338,
      341,  347,  347,  463,  338,  462,  324,  461,  335,  348,
      349,  338,  342,  326,  452,  295,  337,  355,  460,  356,
      356,  356,  356,  356,  356,  371,  371,  372,  371,  371,
      371,  371,  371,  371,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  390,  391,  398,  398,
      399,  398,  398,  398,  398,  398,  398,  371,  371,  372,
      371,  371,  371,  371,  371,  371,  419,  419,  420,  419,
      419,  419,  419,  419,  419,  398,  398,  399,  398,  398,
      398,  398,  398,  398,  422,  423,  470,  471,  449,  424,
      458,  425,  419,  419,  420,  419,  419,  419,  419,  419,
      419,  457,  456,  455,  454,  453,  426,  148,  148,  150,
      150,  351,  351,  373,  373,  400,  400,  371,  371,  421,
      421,  398,  398,  434,  434,  419,  419,  448,  448,  451,
      451,  459,  459,  452,  435,  450,  449,  447,  446,  445,

      444,  443,  442,  441,  440,  420,  439,  438,  437,  436,
      435,  433,  432,  431,  430,  429,  428,  427,  399,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  372,  402,  401,  397,  396,
      395,  394,  393,  392,  389,  388,  352,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  370,  369,  368,  367,  366,  365,  364,  363,  362,
      361,  360,  359,  358,  357,  354,  353,  352,  350,  346,
      345,  344,  343,  340,  339,  333,  332,  331,  330,  329,
      328,  327,  322,  321,  318,  317,  308,  305,  304,  303,

      302,  301,  300,  297,  296,  292,  291,  290,  151,  149,
      288,  287,  286,  285,  284,  283,  282,  280,  279,  278,
      275,  263,  262,  261,  258,  257,  254,  245,  244,  241,
      240,  239,  238,  232,  229,  228,  225,  224,  223,  216,
      215,  214,  211,  206,  205,  204,  200,  199,  194,  189,
      186,  185,  184,  179,  176,  173,  166,  165,  164,  163,
      162,  161,  160,  153,  152,  151,  149,  146,  145,  143,
      141,   87,  477,   45,    3,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477
    } ;

static yyconst flex_int16_t yy_chk[738] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    7,    5,    9,    9,    9,    9,    9,
        9,   10,   10,   10,   10,   10,   10,   10,   11,   11,
       11,   11,   11,   11,   11,   44,   44,   22,   11,   12,
       12,   12,   12,   12,   12,   12,   22,   20,   33,   12,

       13,   13,   13,   13,   13,   13,   13,   15,  478,   14,
       13,   14,   20,   15,    7,  472,    7,   33,   16,    7,
       16,   14,   16,   16,   17,   14,   93,   14,   19,   17,
       16,   46,   16,   46,   19,   18,   17,   18,   16,   17,
       18,   25,   21,   25,   26,   25,   93,   18,   21,   27,
       28,   27,   26,   27,   25,   66,   25,   50,   26,   29,
       66,   50,   28,   27,   26,   28,   27,   27,   27,   29,
       32,  471,   34,   29,   30,   30,   30,   30,   30,   30,
       35,   35,   30,   32,   30,   30,   35,   65,   65,   32,
       34,   34,  470,   35,   30,   35,   57,   57,   30,   31,

       36,   36,  108,   31,  108,   31,   36,   31,   31,   31,
       31,   31,   69,   36,   31,   31,   31,   69,   39,   39,
       57,   31,   31,   31,   39,   31,   67,   67,   41,   41,
       39,   39,   41,  469,   41,   52,   52,   52,   52,   52,
       52,   41,   51,   51,   51,   51,   51,   51,   51,   71,
       71,   73,   73,   73,   77,   77,   95,   79,   79,   81,
       81,  468,   73,   79,   82,   82,   88,   88,   92,   92,
       99,   99,  100,  117,   95,  104,  104,  111,   88,  112,
       79,  466,  100,  121,  100,  110,  100,  110,  110,  117,
      111,  122,  112,  120,  120,  465,  112,  110,  121,  124,

      127,  110,  122,  133,  131,  133,  127,  133,  122,  462,
      120,  132,  132,  133,  124,  131,  461,  133,  133,  135,
      459,  135,  139,  139,  147,  147,  155,  186,  139,  155,
      164,  164,  203,  203,  458,  139,  186,  132,  156,  156,
      156,  156,  156,  156,  215,  215,  216,  216,  156,  219,
      219,  224,  224,  230,  231,  276,  457,  277,  281,  281,
      284,  289,  289,  456,  281,  455,  230,  453,  276,  290,
      290,  281,  284,  231,  451,  156,  277,  295,  450,  295,
      295,  295,  295,  295,  295,  332,  332,  332,  332,  332,
      332,  332,  332,  332,  355,  355,  355,  355,  355,  355,

      356,  356,  356,  356,  356,  356,  357,  357,  365,  365,
      365,  365,  365,  365,  365,  365,  365,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  397,  397,  397,  397,
      397,  397,  397,  397,  397,  400,  400,  400,  400,  400,
      400,  400,  400,  400,  401,  401,  467,  467,  448,  401,
      447,  401,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  444,  443,  442,  439,  438,  401,  479,  479,  480,
      480,  481,  481,  482,  482,  483,  483,  484,  484,  485,
      485,  486,  486,  487,  487,  488,  488,  489,  489,  490,
      490,  491,  491,  436,  434,  433,  432,  429,  428,  427,

      426,  425,  424,  423,  422,  419,  418,  417,  416,  413,
      412,  411,  410,  409,  407,  406,  405,  404,  398,  396,
      395,  393,  391,  390,  389,  388,  387,  386,  385,  384,
      383,  382,  381,  378,  377,  371,  370,  369,  364,  363,
      362,  361,  359,  358,  354,  353,  351,  350,  349,  348,
      346,  345,  344,  343,  342,  341,  340,  339,  337,  335,
      333,  330,  329,  328,  326,  324,  322,  321,  318,  317,
      307,  306,  301,  297,  296,  294,  293,  292,  291,  288,
      287,  286,  285,  283,  282,  268,  264,  259,  257,  251,
      239,  235,  229,  228,  221,  220,  192,  185,  180,  176,

      174,  170,  169,  163,  162,  154,  153,  152,  150,  148,
      146,  145,  144,  143,  142,  141,  140,  138,  137,  136,
      134,  130,  129,  128,  126,  125,  123,  119,  118,  116,
      115,  114,  113,  109,  107,  106,  103,  102,  101,   98,
       97,   96,   94,   91,   90,   89,   87,   85,   80,   78,
       76,   75,   74,   72,   70,   68,   64,   63,   62,   61,
       60,   59,   58,   49,   48,   47,   45,   43,   42,   40,
       38,   24,    3,    2,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[202] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int nvgp4ASM__flex_debug;
int nvgp4ASM__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *nvgp4ASM_text;
#line 1 "nvgp4ASM.l"
/* 
 * Copyright (c) 2013, Liou Jhe-Yu <lioujheyu@gmail.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#line 26 "nvgp4ASM.l"
#include "nvgp4ASM.tab.h"
#include "GPU/instruction_def.h"
#include "GPU/gpu_config.h"

#define COL_NO nvgp4ASM_col+=strlen(nvgp4ASM_text)

unsigned int nvgp4ASM_col = 0;
#line 858 "nvgp4ASM.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int nvgp4ASM_lex_destroy (void );

int nvgp4ASM_get_debug (void );

void nvgp4ASM_set_debug (int debug_flag  );

YY_EXTRA_TYPE nvgp4ASM_get_extra (void );

void nvgp4ASM_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *nvgp4ASM_get_in (void );

void nvgp4ASM_set_in  (FILE * in_str  );

FILE *nvgp4ASM_get_out (void );

void nvgp4ASM_set_out  (FILE * out_str  );

int nvgp4ASM_get_leng (void );

char *nvgp4ASM_get_text (void );

int nvgp4ASM_get_lineno (void );

void nvgp4ASM_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int nvgp4ASM_wrap (void );
#else
extern int nvgp4ASM_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( nvgp4ASM_text, nvgp4ASM_leng, 1, nvgp4ASM_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( nvgp4ASM_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( nvgp4ASM_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, nvgp4ASM_in))==0 && ferror(nvgp4ASM_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(nvgp4ASM_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int nvgp4ASM_lex (void);

#define YY_DECL int nvgp4ASM_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after nvgp4ASM_text and nvgp4ASM_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( nvgp4ASM_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(nvgp4ASM_text[nvgp4ASM_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 35 "nvgp4ASM.l"

#line 1050 "nvgp4ASM.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! nvgp4ASM_in )
			nvgp4ASM_in = stdin;

		if ( ! nvgp4ASM_out )
			nvgp4ASM_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			nvgp4ASM_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				nvgp4ASM__create_buffer(nvgp4ASM_in,YY_BUF_SIZE );
		}

		nvgp4ASM__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of nvgp4ASM_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 478 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 675 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < nvgp4ASM_leng; ++yyl )
				if ( nvgp4ASM_text[yyl] == '\n' )
					   
    nvgp4ASM_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 36 "nvgp4ASM.l"
/* Comment */
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 37 "nvgp4ASM.l"

	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 38 "nvgp4ASM.l"

	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 39 "nvgp4ASM.l"

	YY_BREAK
case 5:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 40 "nvgp4ASM.l"

	YY_BREAK
case 6:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 41 "nvgp4ASM.l"

	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 42 "nvgp4ASM.l"
/* Comment */
	YY_BREAK
case 8:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 43 "nvgp4ASM.l"

	YY_BREAK
case 9:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 44 "nvgp4ASM.l"

	YY_BREAK
case 10:
*yy_cp = (yy_hold_char); /* undo effects of setting up nvgp4ASM_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up nvgp4ASM_text again */
YY_RULE_SETUP
#line 45 "nvgp4ASM.l"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "nvgp4ASM.l"
COL_NO; return PROF;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "nvgp4ASM.l"
COL_NO; nvgp4ASM_lval.ival=0; return SHADERTYPE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "nvgp4ASM.l"
COL_NO; nvgp4ASM_lval.ival=1; return SHADERTYPE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "nvgp4ASM.l"
COL_NO; return END;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "nvgp4ASM.l"
COL_NO;	return TEXTURE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=INTERP_SMOOTH; return INTERP_MODE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=INTERP_FLAT; return INTERP_MODE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=INTERP_CENTROID; return INTERP_MODE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=INTERP_NOPERSPECTIVE; return INTERP_MODE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=INTERP_NORMALIZE; return INTERP_MODE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ABS; return VECTOROP;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_CEIL; return VECTOROP;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_FLR; return VECTOROP;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_FRC; return VECTOROP;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_I2F; return VECTOROP;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_LIT; return VECTOROP;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MOV; return VECTOROP;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_NOT; return VECTOROP;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_NRM; return VECTOROP;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_PK2H; return VECTOROP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_PK2US; return VECTOROP;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_PK4B; return VECTOROP;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_PK4UB; return VECTOROP;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ROUND; return VECTOROP;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SSG; return VECTOROP;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TRUNC; return VECTOROP;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_COS; return SCALAROP;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_EX2; return SCALAROP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_LG2; return SCALAROP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_RCC; return SCALAROP;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_RCP; return SCALAROP;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_RSQ; return SCALAROP;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SCS; return SCALAROP;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SIN; return SCALAROP;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_UP2H; return SCALAROP;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_UP2US; return SCALAROP;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_UP4B; return SCALAROP;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 87 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_UP4UB; return SCALAROP;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 88 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_POW;  return BINSCOP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 89 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DIV; return VECSCAOP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SHL; return VECSCAOP;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SHR; return VECSCAOP;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MOD; return VECSCAOP;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ADD; return BINOP;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_AND; return BINOP;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DP3; return BINOP;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 96 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DP4; return BINOP;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 97 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DPH; return BINOP;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 98 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DST; return BINOP;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MAX; return BINOP;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MIN; return BINOP;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MUL; return BINOP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_OR; return BINOP;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_RFL; return BINOP;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SEQ; return BINOP;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SFL; return BINOP;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SGE; return BINOP;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SGT; return BINOP;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SLE; return BINOP;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SLT; return BINOP;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 110 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SNE; return BINOP;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 111 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_STR; return BINOP;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 112 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SUB; return BINOP;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 113 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_XPD; return BINOP;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 114 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DP2; return BINOP;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 115 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_XOR; return BINOP;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 116 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_CMP; return TRIOP;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 117 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DP2A; return TRIOP;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 118 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_LRP; return TRIOP;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 119 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_MAD; return TRIOP;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 120 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SAD; return TRIOP;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 121 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_X2D; return TRIOP;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 122 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_SWZ; return SWZOP;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 123 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TEX; return TEXOP;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXB; return TEXOP;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXF; return TEXOP;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXL; return TEXOP;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXP; return TEXOP;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 128 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXQ; return TEXOP;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 129 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_TXD; return TXDOP;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 130 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_CAL; return BRAOP;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 131 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_RET; return FLOWCCOP;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 132 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_BRK; return FLOWCCOP;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 133 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_CONT; return FLOWCCOP;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 134 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_IF; return IFOP;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 135 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_REP; return REPOP;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 136 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ELSE; return ENDFLOWOP;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 137 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ENDIF; return ENDFLOWOP;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 138 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_ENDREP; return ENDFLOWOP;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 139 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_KIL; return KILOP;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 140 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DDX; return DERIVEOP;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 141 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OP_DDY; return DERIVEOP;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 142 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_F; return OPMODIFIER;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 143 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_U; return OPMODIFIER;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 144 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_S; return OPMODIFIER;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 145 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_CC; return OPMODIFIER;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 146 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_CC0; return OPMODIFIER;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 147 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_CC1; return OPMODIFIER;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 148 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_SAT; return OPMODIFIER;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 149 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_SSAT; return OPMODIFIER;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 150 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_NTC; return OPMODIFIER;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 151 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_S24; return OPMODIFIER;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 152 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_U24; return OPMODIFIER;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 153 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=OPM_HI; return OPMODIFIER;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 154 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_1D; return TEXTARGET;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 155 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_2D; return TEXTARGET;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 156 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_3D; return TEXTARGET;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 157 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_CUBE; return TEXTARGET;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 158 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_RECT; return TEXTARGET;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 159 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOW1D; return TEXTARGET;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 160 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOW2D; return TEXTARGET;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 161 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOWRECT; return TEXTARGET;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 162 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_ARRAY1D; return TEXTARGET;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 163 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_ARRAY2D; return TEXTARGET;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 164 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOWCUBE; return TEXTARGET;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 165 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOWARRAY1D; return TEXTARGET;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 166 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=TT_SHADOWARRAY2D; return TEXTARGET;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 167 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_EQ; return CCMASKRULE;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 168 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GE; return CCMASKRULE;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 169 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GT; return CCMASKRULE;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 170 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LE; return CCMASKRULE;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 171 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LT; return CCMASKRULE;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 172 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NE; return CCMASKRULE;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 173 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_TR; return CCMASKRULE;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 174 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_FL; return CCMASKRULE;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 175 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_EQ0; return CCMASKRULE;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 176 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GE0; return CCMASKRULE;
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 177 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GT0; return CCMASKRULE;
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 178 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LE0; return CCMASKRULE;
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 179 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LT0; return CCMASKRULE;
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 180 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NE0; return CCMASKRULE;
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 181 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_TR0; return CCMASKRULE;
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 182 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_FL0; return CCMASKRULE;
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 183 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_EQ1; return CCMASKRULE;
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 184 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GE1; return CCMASKRULE;
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 185 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_GT1; return CCMASKRULE;
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 186 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LE1; return CCMASKRULE;
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 187 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LT1; return CCMASKRULE;
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 188 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NE1; return CCMASKRULE;
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 189 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_TR1; return CCMASKRULE;
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 190 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_FL1; return CCMASKRULE;
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 191 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NAN; return CCMASKRULE;
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 192 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NAN0; return CCMASKRULE;
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 193 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NAN1; return CCMASKRULE;
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 194 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LEG; return CCMASKRULE;
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 195 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LEG0; return CCMASKRULE;
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 196 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_LEG1; return CCMASKRULE;
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 197 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_CF; return CCMASKRULE;
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 198 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_CF0; return CCMASKRULE;
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 199 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_CF1; return CCMASKRULE;
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 200 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NCF; return CCMASKRULE;
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 201 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NCF0; return CCMASKRULE;
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 202 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NCF1; return CCMASKRULE;
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 203 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_OF; return CCMASKRULE;
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 204 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_OF0; return CCMASKRULE;
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 205 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_OF1; return CCMASKRULE;
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 206 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NOF; return CCMASKRULE;
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 207 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NOF0; return CCMASKRULE;
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 208 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NOF1; return CCMASKRULE;
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 209 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_AB; return CCMASKRULE;
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 210 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_AB0; return CCMASKRULE;
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 211 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_AB1; return CCMASKRULE;
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 212 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_BLE; return CCMASKRULE;
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 213 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_BLE0; return CCMASKRULE;
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 214 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_BLE1; return CCMASKRULE;
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 215 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_SF; return CCMASKRULE;
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 216 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_SF0; return CCMASKRULE;
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 217 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_SF1; return CCMASKRULE;
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 218 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NSF; return CCMASKRULE;
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 219 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NSF0; return CCMASKRULE;
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 220 "nvgp4ASM.l"
COL_NO;	nvgp4ASM_lval.ival=CC_NSF1; return CCMASKRULE;
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 221 "nvgp4ASM.l"
COL_NO; return VERTEX;
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 222 "nvgp4ASM.l"
COL_NO; return FRAGMENT;
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 223 "nvgp4ASM.l"
COL_NO; return RESULT;
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 224 "nvgp4ASM.l"
COL_NO; return ATTRIB;
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 225 "nvgp4ASM.l"
COL_NO; return ATTRIB;
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 226 "nvgp4ASM.l"
COL_NO; return POSITION;
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 227 "nvgp4ASM.l"
COL_NO; return RESULT_COLOR0;
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 228 "nvgp4ASM.l"
COL_NO;	return *nvgp4ASM_text;
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 229 "nvgp4ASM.l"
COL_NO; nvgp4ASM_lval.ival=-1; return REG;
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 230 "nvgp4ASM.l"
COL_NO; nvgp4ASM_lval.ival=-1; return REG;
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 232 "nvgp4ASM.l"
{ COL_NO;
		char *temp = nvgp4ASM_text+1;
		nvgp4ASM_lval.ival=atoi(temp);
		return REG;
	}
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 237 "nvgp4ASM.l"
{ COL_NO;
		strcpy(nvgp4ASM_lval.sval,nvgp4ASM_text);
		return XYZW_SWIZZLE;
	}
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 241 "nvgp4ASM.l"
{ COL_NO;
		strcpy(nvgp4ASM_lval.sval,nvgp4ASM_text);
		return RGBA_SWIZZLE;
	}
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 245 "nvgp4ASM.l"
{ COL_NO;
		strcpy(nvgp4ASM_lval.sval,nvgp4ASM_text);
		return IDENTIFIER;
	}
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 249 "nvgp4ASM.l"
{ COL_NO;
		nvgp4ASM_lval.ival = atoi(nvgp4ASM_text);
		return INTEGER;
	}
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 253 "nvgp4ASM.l"
{ COL_NO;
		nvgp4ASM_lval.fval = atof(nvgp4ASM_text);
		return FLOAT;
	}
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 257 "nvgp4ASM.l"
COL_NO; return *nvgp4ASM_text;
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 259 "nvgp4ASM.l"
COL_NO;		/* remove all space-related char */
	YY_BREAK
case 200:
/* rule 200 can match eol */
YY_RULE_SETUP
#line 260 "nvgp4ASM.l"
nvgp4ASM_col = 0;
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 261 "nvgp4ASM.l"
ECHO;
	YY_BREAK
#line 2199 "nvgp4ASM.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed nvgp4ASM_in at a new source and called
			 * nvgp4ASM_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = nvgp4ASM_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( nvgp4ASM_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * nvgp4ASM_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of nvgp4ASM_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					nvgp4ASM_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			nvgp4ASM_restart(nvgp4ASM_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) nvgp4ASM_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 478 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 478 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 477);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up nvgp4ASM_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --nvgp4ASM_lineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					nvgp4ASM_restart(nvgp4ASM_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( nvgp4ASM_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve nvgp4ASM_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    nvgp4ASM_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void nvgp4ASM_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        nvgp4ASM_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            nvgp4ASM__create_buffer(nvgp4ASM_in,YY_BUF_SIZE );
	}

	nvgp4ASM__init_buffer(YY_CURRENT_BUFFER,input_file );
	nvgp4ASM__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void nvgp4ASM__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		nvgp4ASM_pop_buffer_state();
	 *		nvgp4ASM_push_buffer_state(new_buffer);
     */
	nvgp4ASM_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	nvgp4ASM__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (nvgp4ASM_wrap()) processing, but the only time this flag
	 * is looked at is after nvgp4ASM_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void nvgp4ASM__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	nvgp4ASM_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE nvgp4ASM__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) nvgp4ASM_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) nvgp4ASM_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM__create_buffer()" );

	b->yy_is_our_buffer = 1;

	nvgp4ASM__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with nvgp4ASM__create_buffer()
 * 
 */
    void nvgp4ASM__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		nvgp4ASM_free((void *) b->yy_ch_buf  );

	nvgp4ASM_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a nvgp4ASM_restart() or at EOF.
 */
    static void nvgp4ASM__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	nvgp4ASM__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then nvgp4ASM__init_buffer was _probably_
     * called from nvgp4ASM_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void nvgp4ASM__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		nvgp4ASM__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void nvgp4ASM_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	nvgp4ASM_ensure_buffer_stack();

	/* This block is copied from nvgp4ASM__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from nvgp4ASM__switch_to_buffer. */
	nvgp4ASM__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void nvgp4ASM_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	nvgp4ASM__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		nvgp4ASM__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void nvgp4ASM_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)nvgp4ASM_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)nvgp4ASM_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE nvgp4ASM__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) nvgp4ASM_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	nvgp4ASM__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to nvgp4ASM_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       nvgp4ASM__scan_bytes() instead.
 */
YY_BUFFER_STATE nvgp4ASM__scan_string (yyconst char * yystr )
{
    
	return nvgp4ASM__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to nvgp4ASM_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE nvgp4ASM__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) nvgp4ASM_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in nvgp4ASM__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = nvgp4ASM__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in nvgp4ASM__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nvgp4ASM_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		nvgp4ASM_text[nvgp4ASM_leng] = (yy_hold_char); \
		(yy_c_buf_p) = nvgp4ASM_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		nvgp4ASM_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int nvgp4ASM_get_lineno  (void)
{
        
    return nvgp4ASM_lineno;
}

/** Get the input stream.
 * 
 */
FILE *nvgp4ASM_get_in  (void)
{
        return nvgp4ASM_in;
}

/** Get the output stream.
 * 
 */
FILE *nvgp4ASM_get_out  (void)
{
        return nvgp4ASM_out;
}

/** Get the length of the current token.
 * 
 */
int nvgp4ASM_get_leng  (void)
{
        return nvgp4ASM_leng;
}

/** Get the current token.
 * 
 */

char *nvgp4ASM_get_text  (void)
{
        return nvgp4ASM_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void nvgp4ASM_set_lineno (int  line_number )
{
    
    nvgp4ASM_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see nvgp4ASM__switch_to_buffer
 */
void nvgp4ASM_set_in (FILE *  in_str )
{
        nvgp4ASM_in = in_str ;
}

void nvgp4ASM_set_out (FILE *  out_str )
{
        nvgp4ASM_out = out_str ;
}

int nvgp4ASM_get_debug  (void)
{
        return nvgp4ASM__flex_debug;
}

void nvgp4ASM_set_debug (int  bdebug )
{
        nvgp4ASM__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from nvgp4ASM_lex_destroy(), so don't allocate here.
     */

    /* We do not touch nvgp4ASM_lineno unless the option is enabled. */
    nvgp4ASM_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    nvgp4ASM_in = stdin;
    nvgp4ASM_out = stdout;
#else
    nvgp4ASM_in = (FILE *) 0;
    nvgp4ASM_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * nvgp4ASM_lex_init()
     */
    return 0;
}

/* nvgp4ASM_lex_destroy is for both reentrant and non-reentrant scanners. */
int nvgp4ASM_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		nvgp4ASM__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		nvgp4ASM_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	nvgp4ASM_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * nvgp4ASM_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *nvgp4ASM_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *nvgp4ASM_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void nvgp4ASM_free (void * ptr )
{
	free( (char *) ptr );	/* see nvgp4ASM_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 261 "nvgp4ASM.l"



void nvgp4ASM_error(char *s)
{
    printf("(%d,%d) %s at %s\n",
			nvgp4ASM_lineno,
			nvgp4ASM_col,
			s,
			nvgp4ASM_text);
}

void nvgp4ASM_str_in(const char *s)
{
	nvgp4ASM__scan_string(s);
}


