#ifndef GPU_CONFIG_H_INCLUDED
#define GPU_CONFIG_H_INCLUDED

#define MAX_ATTRIBUTE_NUMBER    8

#define VPNEAR 	    0.0
#define VPFAR 	    1.0

#define PIXEL_GENERATE_DEBUG

#define TEX_CACHE_BLOCK_SIZE_ROOT_LOG 2
#define TEX_CACHE_BLOCK_SIZE_ROOT 4
#define TEX_CACHE_BLOCK_SIZE 16
#define TEX_CACHE_ENTRY_X_LOG 2
#define TEX_CACHE_ENTRY_X 4
#define TEX_CACHE_ENTRY_Y_LOG 2
#define TEX_CACHE_ENTRY_Y 4

#endif // GPU_CONFIG_H_INCLUDED
